homePage:
   path: /
   controller: \App\Controller\PostController
   action: home

articlePage:
   path: /article/{id}
   controller: \App\Controller\PostController
   action: article

createArticle:
   path: /createArticle
   controller: \App\Controller\PostController
   action: createArticle

modifyArticle:
   path: /modifyArticle/{id}
   controller: \App\Controller\PostController
   action: modifyArticle

deleteArticle:
   path: /deleteArticle/{id}
   controller: \App\Controller\PostController
   action: deleteArticle

usersPage:
   path: /users
   controller: \App\Controller\UserController
   action: users

singleUserPage:
   path: /user/{id}
   controller: \App\Controller\UserController
   action: user

modifyUser:
   path: /modifyUser/{id}
   controller: \App\Controller\UserController
   action: modifyUser

deleteUser:
   path: /deleteUser/{id}
   controller: \App\Controller\UserController
   action: deleteUser

showOne:
   path: /show/{id}-{truc}
   controller: \App\Controller\PostController
   action: show

showTest:
   path: /show
   controller: \App\Controller\PostController
   action: showTest

login:
   path: /login
   controller: \App\Controller\LoginController
   action: login


login2:
   path: /login2
   controller: \App\Controller\Login2Controller
   action: login2

logout:
   path: /logout
   controller: \App\Controller\LogoutController
   action: logout